name: Build Flutter APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Upgrade Gradle
        run: |
          sed -i 's#gradle-[0-9.]*-all.zip#gradle-8.14.4-all.zip#' android/gradle/wrapper/gradle-wrapper.properties

      - name: Upgrade Android Gradle Plugin
        run: |
          sed -i 's/id("com.android.application") version "[0-9.]*"/id("com.android.application") version "8.11.1"/' android/settings.gradle.kts

      - name: Upgrade Kotlin
        run: |
          sed -i 's/id("org.jetbrains.kotlin.android") version "[0-9.]*"/id("org.jetbrains.kotlin.android") version "2.2.20"/' android/settings.gradle.kts

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk
